services:
  nextjs-app:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: |
      sh -c "yarn install && yarn build && yarn start & echo 'Docker image is serving the application at http://localhost:8081 or https://localhost:8080' && tail -f /dev/null"

  nginx:
    image: nginx:latest
    ports:
      - "8080:443"
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl
    depends_on:
      - nextjs-app
    entrypoint: sh -c "mkdir -p /etc/nginx/ssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/localhost.key -out /etc/nginx/ssl/localhost.crt -subj '/CN=localhost' && nginx -g 'daemon off;'"