services:
  nextjs-app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: |
      sh -c "yarn install && yarn build && yarn start & echo 'Docker image is serving the application at http://localhost:8080' && tail -f /dev/null"